name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      issues: write
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      env:
        API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        image: nmap-image:latest
        run: |
          echo "Yes we scan"
          export REPO_URL=${{ github.repository }}
          #export API_TOKEN=${{ secrets.ApiToken }}
          
          echo "[INFO] Upload nmap output as issue to GitHub"
          title="Yes we scanned on $(date "+%D %T")"
          body=$(sed '1d;s/"/\\"/g;:a;N;$!ba;s/\n/\\n/g' /tmp/outputfile.txt)
          payload="{\"title\":\"$title\",\"body\":\"$body\"}"

          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "$title",
            "body": "$body"
            }' \
          --fail
          bash entrypoint.sh
