name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      issues: write
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      env:
        API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        image: nmap-image:latest
        run: |
          echo "Yes we scan"
          export REPO_URL=${{ github.repository }}
          #export API_TOKEN=${{ secrets.ApiToken }}
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
          bash entrypoint.sh
