name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_URL: ${{ github.repository }}
    permissions:
      issues: write
      contents: read
      packages: write
    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3

      with:
        image: nmap-image:latest
        run: |
          echo "Yes we scan"
          export GITHUB_TOKEN=${{ GITHUB_TOKEN }}
          export REPO_URL=${{ REPO_URL }}
          bash entrypoint.sh
          cat /tmp/outputfile.txt
