name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      issues: write
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        image: nmap-image:latest
        run: |
          echo "Yes we scan"
          export REPO_URL=${{ github.repository }}
          export API_TOKEN=${{ secrets.ApiToken }}
          bash entrypoint.sh
