name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_URL: ${{ github.repository }}
    permissions:
      issues: write
      contents: read
      packages: write
    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        image: nmap-image:latest
        run: |
          gh api /octocat
          
          echo "Yes we scan"
          bash entrypoint.sh
          
          echo "========================================================"
          test=$(sed 's/|/\n&/g' /tmp/outputfile.txt)
          echo $test
          echo "========================================================"
          
          curl -v --request POST \
               --url https://api.github.com/repos/${{ github.repository }}/issues \
               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'content-type: application/json' \
               --data '{
                  "title": "Yes we scanned",
                  "body": $test
                  }' \
               --fail  
          
