name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      packages: write
    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_URL: ${{ github.repository }}
      with:
        image: nmap-image:latest
        run: |
          echo "Yes we scan"
          bash entrypoint.sh
