name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_URL: ${{ github.repository }}
    permissions:
      issues: write
      contents: read
      packages: write
    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: nmap-image:latest
        run: |
          bash entrypoint.sh
          
          # Push Findings as GH Issue 
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}

          now=$(date "+%D %T")
          title="Yes we scanned on $now"
          
          gh auth login
          cd /tmp
          gh repo clone BenjiTrapp/yes-we-scan
          cd yes-we-scan
          gh issue create --title "${title}" --body-file /tmp/outputfile.txt
