name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.nmap.outputs.data }}
      title: ${{ steps.nmap}}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_URL: ${{ github.repository }}
    permissions:
      issues: write
      contents: read
      packages: write
    steps:
    - uses: docker/build-push-action@v2
      id: push
      with:
        tags: nmap-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      id: nmap
      with:
        image: nmap-image:latest
        run: |
          bash entrypoint.sh
          
          now=$(date "+%D %T")
          title="Yes we scanned on $now"
          data=$(cat /tmp/outputfile.txt)
          
          echo "data=$data" >> $GITHUB_OUTPUT
  push:
      runs-on: ubuntu-latest
      needs: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_URL: ${{ github.repository }}
      permissions:
        issues: write
        contents: read
        packages: write
      steps:
        - run: echo ${{ needs.build.outputs.data }} >> /tmp/data.txt
        - uses: exuanbo/actions-deploy-gist@v1
          id: gist
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            gist_id: d59f4ff64cadbc8f25f218ea5acaa35e
            file_path: /tmp/data.txt
            file_type: binary

        